### PR TITLE
fix(eth/peer/wit): concurrent data read/write cases

### LINKED ISSUE #1729: Data race on ethPeer field between doWitnessRequest writer and RequestWitnesses reader
Concurrent access to ethPeer field at 0x00c000f37f68. Write occurs in doWitnessRequest (peer.go:454) while read happens in RequestWitnesses (peer.go:200). Race between goroutines spawned by witnessManager during witness fetching operations.

https://github.com/0xPolygon/bor/commit/8509ba2

```
==================
WARNING: DATA RACE
Write at 0x00c000f37f68 by goroutine 268:
  github.com/ethereum/go-ethereum/eth.(*ethPeer).doWitnessRequest()
      /var/lib/bor/eth/peer.go:454 +0x884
  github.com/ethereum/go-ethereum/eth.(*ethPeer).buildWitnessRequests()
      /var/lib/bor/eth/peer.go:385 +0x649
  github.com/ethereum/go-ethereum/eth.(*ethPeer).RequestWitnesses.func1()
      /var/lib/bor/eth/peer.go:180 +0x130

Previous read at 0x00c000f37f68 by goroutine 267:
  github.com/ethereum/go-ethereum/eth.(*ethPeer).RequestWitnesses()
      /var/lib/bor/eth/peer.go:200 +0x9c4
  github.com/ethereum/go-ethereum/eth.(*ethHandler).handleBlockBroadcast.func1()
      /var/lib/bor/eth/handler_eth.go:162 +0xc9
  github.com/ethereum/go-ethereum/eth/fetcher.(*witnessManager).fetchWitness()
      /var/lib/bor/eth/fetcher/witness_manager.go:522 +0x130
  github.com/ethereum/go-ethereum/eth/fetcher.(*witnessManager).tick.gowrap1()
      /var/lib/bor/eth/fetcher/witness_manager.go:507 +0xaa

Goroutine 268 (running) created at:
  github.com/ethereum/go-ethereum/eth.(*ethPeer).RequestWitnesses()
      /var/lib/bor/eth/peer.go:179 +0x73c
  github.com/ethereum/go-ethereum/eth.(*ethHandler).handleBlockBroadcast.func1()
      /var/lib/bor/eth/handler_eth.go:162 +0xc9
  github.com/ethereum/go-ethereum/eth/fetcher.(*witnessManager).fetchWitness()
      /var/lib/bor/eth/fetcher/witness_manager.go:522 +0x130
  github.com/ethereum/go-ethereum/eth/fetcher.(*witnessManager).tick.gowrap1()
      /var/lib/bor/eth/fetcher/witness_manager.go:507 +0xaa

Goroutine 267 (running) created at:
  github.com/ethereum/go-ethereum/eth/fetcher.(*witnessManager).tick()
      /var/lib/bor/eth/fetcher/witness_manager.go:507 +0x25a4
  github.com/ethereum/go-ethereum/eth/fetcher.(*witnessManager).loop()
      /var/lib/bor/eth/fetcher/witness_manager.go:216 +0xc9b
  github.com/ethereum/go-ethereum/eth/fetcher.(*witnessManager).start.gowrap2()
      /var/lib/bor/eth/fetcher/witness_manager.go:142 +0x33
==================
INFO [08-28|00:45:09.578] Whitelisting milestone deferred          err="chain out of sync"

```

```
{
  "IPT_bytes_out": 16994920,
  "output_text": "WARNING: DATA RACE",
  "source": {
    "container": "l2-el-4-bor-heimdall-v2-rpc--b97cb9deb4cc4b4fbfd625abd50535e6",
    "name": "l2-el-4-bor-heimdall-v2-rpc--b97cb9deb4cc4b4fbfd625abd50535e6",
    "stream": "error"
  },
  "moment": {
    "input_hash": "5474484343311274565",
    "_vtime_ticks": 657727462115,
    "session_id": "c0ceefcd588ee0d629772f6fd9eae1ec-36-12"
  }
}
```

### PR DESCRIPTION
**Pull request by kamuikatsurgi**
Fixes #1729 and #1736 

# Description

Issue in #1729:

The original code had a data race between:
- READ: where we read `witReqs` to create `wrapperReq := &ethWitRequest{Request: ethReqShim, witReqs: witReqs}`.
- WRITE: where `doWitnessRequest()` does `*witReqs = append(*witReqs, witReq)`

The race occurred because `buildWitnessRequests` was called asynchronously in a goroutine, allowing the main goroutine to read witReqs while the background goroutine was still populating it via append operations.

By calling `buildWitnessRequests` synchronously, we ensure all initial witness requests are built and appended to `witReqs` BEFORE the main goroutine reads the slice, eliminating the possibility of concurrent read/write access.

Issue in #1736:

The original code had a data race between:
- READ: where we read `announce.time` for logging/timestamping
- WRITE: `handleWitnessFetchFailureExt()` where it does `state.announce.time = time.Now().Add(fetchTimeout)`

The race occurred because this read was unprotected while `handleWitnessFetchFailureExt()` was writing to the same `announce.time` field under mutex protection. Both operations access the same memory location but with different synchronisation. By protecting this read with the same mutex used by the writer, we ensure synchronised access to announce. time, eliminating the data race.

### CODE REVIEW

File: eth/peer.go [hunk 1]
```diff
@@ -174,17 +174,19 @@ func (p *ethPeer) RequestWitnesses(hashes []common.Hash, dlResCh chan *eth.Respo
...
+	// Build all the initial requests and wait for them to complete.
 	witReqsWg.Add(1)
 	go func() {
 		p.buildWitnessRequests(hashes, &witReqs, &witReqsWg, witTotalPages, witTotalRequest, witReqResCh, witReqSem, &mapsMu, &buildRequestMu, failedRequests)
 		witReqsWg.Done()
 	}()
 
-	// closes witResCh after all requests are done
+	// Wait for all the initial requests to be built.
+	witReqsWg.Wait()
```
Comment (kamuikatsurgi) [inline eth/peer.go]: The data race occurred because the main goroutine was reading the `witReqs` while a background goroutine was concurrently modifying it.
```go
var witReqs []*wit.Request
go func() {
    buildWitnessRequests(..., &witReqs, ...)
    witReqsWg.Done()
}()

go func() {
    defer close(witReqResCh)
    witReqsWg.Wait()
}()

wrapperReq := &ethWitRequest{
    witReqs: witReqs,
}
```

The issue was that `witReqsWg.Wait()` was placed inside a separate goroutine for closing channels, which didn't help the main goroutine. Meanwhile, the background goroutine was doing:
```go
*witReqs = append(*witReqs, witReq)
```

While the main goroutine was doing:
```go
witReqs: witReqs,
```

The fix moved the wait to the main goroutine:
```go
var witReqs []*wit.Request
go func() {
    buildWitnessRequests(..., &witReqs, ...)
    witReqsWg.Done()
}()

witReqsWg.Wait()

wrapperReq := &ethWitRequest{
    witReqs: witReqs,
}
```

**Review by lucca30 — APPROVED** [review]
lgtm!
