### PR TITLE
MAT-872: Fix import/export state with bor

### LINKED ISSUE #27: Import state doesn't work with Bor consensus
**Error details**

Since Bor uses `consensus/bor.go` consensus, it is failing while fetching the validators

```
INFO [03-15|23:09:37.578] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [03-15|23:09:37.581] Maximum peer count                       ETH=50 LES=0 total=50
INFO [03-15|23:09:37.607] Allocated cache and file handles         database=/Users/jdkanani/matic/testnets/bor-devnet/node1/bor/chaindata cache=2.00GiB handles=5120
INFO [03-15|23:09:37.695] Opened ancient database                  database=/Users/jdkanani/matic/testnets/bor-devnet/node1/bor/chaindata/ancient
INFO [03-15|23:09:38.040] Loaded most recent local header          number=0 hash=13b5e3…d73f00 td=1 age=10mo7h7m
INFO [03-15|23:09:38.040] Loaded most recent local full block      number=0 hash=13b5e3…d73f00 td=1 age=10mo7h7m
INFO [03-15|23:09:38.040] Loaded most recent local fast block      number=0 hash=13b5e3…d73f00 td=1 age=10mo7h7m
INFO [03-15|23:09:38.040] Importing blockchain                     file=state.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4705b40]

goroutine 68 [running]:
github.com/maticnetwork/bor/internal/ethapi.(*PublicBlockChainAPI).Call(0x0, 0x5028e00, 0xc0000dc600, 0x0, 0xc0001d3540, 0xc00017a0c0, 0x0, 0x0, 0xc000176400, 0x0, ...)
	/Users/jdkanani/go/src/github.com/maticnetwork/bor/build/_workspace/src/github.com/maticnetwork/bor/internal/ethapi/api.go:815 +0x50
github.com/maticnetwork/bor/consensus/bor.(*Bor).GetCurrentValidators(0xc0000eec60, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jdkanani/go/src/github.com/maticnetwork/bor/build/_workspace/src/github.com/maticnetwork/bor/consensus/bor/bor.go:950 +0x4cb
github.com/maticnetwork/bor/consensus/bor.(*Bor).snapshot(0xc0000eec60, 0x502f880, 0xc04259e000, 0x0, 0x6b9ccba97fe3b513, 0x5870f002ceeed546, 0x1da4cb9ecc22c5f8, 0x3fd7582f6f6e08, 0xc01d456c30, 0x0, ...)
	/Users/jdkanani/go/src/github.com/maticnetwork/bor/build/_workspace/src/github.com/maticnetwork/bor/consensus/bor/bor.go:469 +0x4ea
github.com/maticnetwork/bor/consensus/bor.(*Bor).verifyCascadingFields(0xc0000eec60, 0x502f880, 0xc04259e000, 0xc0001a7680, 0xc01d456c30, 0x0, 0x5, 0x0, 0x0)
	/Users/jdkanani/go/src/github.com/maticnetwork/bor/build/_workspace/src/github.com/maticnetwork/bor/consensus/bor/bor.go:403 +0x151
github.com/maticnetwork/bor/consensus/bor.(*Bor).verifyHeader(0xc0000eec60, 0x502f880, 0xc04259e000, 0xc0001a7680, 0xc01d456c30, 0x0, 0x5, 0x0, 0x0)
	/Users/jdkanani/go/src/github.com/maticnetwork/bor/build/_workspace/src/github.com/maticnetwork/bor/consensus/bor/bor.go:372 +0x288
github.com/maticnetwork/bor/consensus/bor.(*Bor).VerifyHeaders.func1(0xc01d456c30, 0x5, 0x5, 0xc0000eec60, 0x502f880, 0xc04259e000, 0xc000406420, 0xc000105020)
	/Users/jdkanani/go/src/github.com/maticnetwork/bor/build/_workspace/src/github.com/maticnetwork/bor/consensus/bor/bor.go:308 +0xa5
created by github.com/maticnetwork/bor/consensus/bor.(*Bor).VerifyHeaders
	/Users/jdkanani/go/src/github.com/maticnetwork/bor/build/_workspace/src/github.com/maticnetwork/bor/consensus/bor/bor.go:306 +0xda
```

**Reproduction steps**

Export state

```
bor --datadir /Users/jdkanani/matic/testnets/bor-devnet/node1 export state.json
```

Import state in clean bor setup

```
bor --datadir /Users/jdkanani/matic/testnets/bor-devnet/node1 import state.json
```

**Version**

Branch: `master`

### PR DESCRIPTION
**Pull request by atvanguard**
Fixes #27 

Steps:
- Keep node1 running awhile, then kill it.
- Export state (all following commands from `bor-devnet` dir)
```
bor --datadir node1 export state.json ../genesis-contracts/genesis.json
```
- Create node and import state
```
bor --datadir node4 init ../genesis-contracts/genesis.json
cp keystore4/* node4/keystore/
bor --datadir node4 import state.json ../genesis-contracts/genesis.json
```

### CODE REVIEW

File: cmd/utils/flags.go [hunk 1]
```diff
@@ -1702,6 +1749,9 @@ func MakeChain(ctx *cli.Context, stack *node.Node) (chain *core.BlockChain, chai
 	}
 	vmcfg := vm.Config{EnablePreimageRecording: ctx.GlobalBool(VMEnableDebugFlag.Name)}
 	chain, err = core.NewBlockChain(chainDb, cache, config, engine, vmcfg, nil)
+	if ethereum != nil {
```
Comment (jdkanani) [inline cmd/utils/flags.go:1752]: Nicely done 👍
